#!/usr/bin/env bash
# Configure Nginx so that itsends traffic to web-01 nd web-02
# Make sure that HAproxy can be managed via an init script
# Configure HAProxy
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get -y update

# Install HAProxy
sudo apt-get -y install haproxy
sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver 70060-web-01 3.85.136.30:80 check\n\tserver 70060-web-02 100.25.142.15:80 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
