#!/usr/bin/env bash
#a Bash script that displays the content of the file /etc/passwd

name="/etc/passwd"
i=0
lines=0
IFS=':'

if test -f $name; then
  lines="$(wc -l < $name)"
  content=('username' 'password' 'user_id' 'group_id' 'user_id_info' 'home_dir' 'command')
  while [[ $i -lt $lines ]]; do
    i="$((i + 1))"
    read -r -a content < <(tail -n 1 <(head -n $i < $name))
    echo "$content[0]}:${content[2]}:${content[5]}"
  done
fi
