#!/usr/bin/env bash
#This Displays "Best School" 10 times using While-Loop.
#displays "Hi" on the 9th loop

num=0
while [ $num -le 10 ]
do
  if [ $num -eq 9 ]
  then
    echo "Hi"
  fi
  echo "Best School"
  (( num++ ))
done
